name: frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Animations & UI
  animations: ^2.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  share_plus: ^11.1.0

  # Utilities
  path_provider: ^2.1.5
  url_launcher: ^6.3.0
  device_info_plus: ^11.0.0
  webview_flutter: ^4.10.0
  http: ^1.5.0
  json_annotation: ^4.9.0

  # Firebase (aligned versions)
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_messaging: 16.0.1   # <- upgraded to match firebase_core

  # Maps & Location
  google_maps_flutter: ^2.3.0
  geolocator: ^10.0.1
  # Local storage / realtime
  shared_preferences: ^2.3.2
  socket_io_client: ^2.0.0
  vector_math: ^2.2.0
  vibration: ^3.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Flutter specific settings (assets go here at top level)
flutter:
  uses-material-design: true

  assets:
    - assets/images/menu.png
    - assets/icons/logo.png
    - assets/im7.jpg
